apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: road
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
    segment.bytes: 1073741824
    max.message.bytes: 7000000
    max.request.size: 7500000
