apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: socialharvester
spec:
  createingress: true
  functionref:
    functionweights: null
    name: socialharvester
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /socialharvester
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /socialharvester
